on:
  pull_request:

jobs:
  client-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install Client Dependencies
        working-directory: ./client
        run: pnpm ci
      - name: Client Build Check
        working-directory: ./client
        run: pnpm build
