name: lint

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: "9"
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: pnpm
          cache-dependency-path: ./client/pnpm-lock.yaml
      - name: Install dependencies (no-frozen-lockfile)
        working-directory: ./client
        run: pnpm install --no-frozen-lockfile
      - name: Install dependencies
        working-directory: ./client
        run: pnpm install
      - name: Run lint
        working-directory: ./client
        run: pnpm lint
